---
stages:
- check
- compile
- test
variables:
  UNITY_PROJ_REL_PATH: Project
  PYTHON_CI_REPO_PATH: C:\sp-tools-Python-CI-Scripts
  GIT_SUBMODULE_STRATEGY: normal
  GIT_SSL_NO_VERIFY: 1
Check_Merge_Conflict_Markers:
  only:
  - triggers
  script:
  - call C:\conf.bat & set PYTHONPATH=%PYTHON_CI_REPO_PATH% & python -m MergeConflictChecker.CheckMergeConflicts
  stage: check
Copy_New_Branch_Cache:
  only:
  - triggers
  script:
  - python %PYTHON_CI_REPO_PATH%\GenericJobs\CopyCache.py -s master
  stage: compile
Create_UnityCache_Android:
  artifacts:
    paths:
    - '%CI_PROJECT_DIR%/UnityLog/'
    when: on_failure
    expire_in: 4 weeks
  cache:
    key: '%CI_COMMIT_REF_NAME%/AndroidLib/'
    paths:
    - '%UNITY_PROJ_REL_PATH%/Library/'
  only:
  - triggers
  script:
  - python %PYTHON_CI_REPO_PATH%\UnityGenericCall\UnityImportProject.py -buildTarget
    android
  stage: compile
  tags:
  - android
Create_UnityCache_iOS:
  artifacts:
    paths:
    - '%CI_PROJECT_DIR%/UnityLog/'
    when: on_failure
    expire_in: 4 weeks
  cache:
    key: '%CI_COMMIT_REF_NAME%/iOSLib/'
    paths:
    - '%UNITY_PROJ_REL_PATH%/Library/'
  only:
  - triggers
  script:
  - python %PYTHON_CI_REPO_PATH%\UnityGenericCall\UnityImportProject.py -buildTarget
    ios
  stage: compile
  tags:
  - ios

Authoritative_Server_Compile:
  only:
  - triggers
  script:
  - python %PYTHON_CI_REPO_PATH%\StandaloneCSharpCompilerCall\CompileSlnCaller.py
  stage: test
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    SLN_FILE_RELATIVE_PATH: Project/Standalone/Photon/AuthoritativeGameLogic/AuthoritativeGameLogic.sln
    UNITY_PROJ_REL_PATH: Project
    WARN_AS_ERROR: 0

Lockstep_Server_Compile:
  only:
  - triggers
  script:
  - python %PYTHON_CI_REPO_PATH%\StandaloneCSharpCompilerCall\CompileSlnCaller.py
  stage: test
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    SLN_FILE_RELATIVE_PATH: Project/Standalone/Photon/LockstepGameLogic/LockstepGameLogic.sln
    UNITY_PROJ_REL_PATH: Project
    WARN_AS_ERROR: 0

Android_Unity_Tests:
  artifacts:
    paths:
    - '%CI_PROJECT_DIR%/UnityLog/'
    when: always
  cache:
    key: '%CI_COMMIT_REF_NAME%/AndroidLib/'
    paths:
    - '%UNITY_PROJ_REL_PATH%/Library/'
    policy: pull
  only:
  - triggers
  script:
  - python %PYTHON_CI_REPO_PATH%\UnityGenericCall\UnityTestsCall.py -buildTarget
    android
  stage: test
  tags:
  - android
iOS_Unity_Tests:
  artifacts:
    paths:
    - '%CI_PROJECT_DIR%/UnityLog/'
    when: always
  cache:
    key: '%CI_COMMIT_REF_NAME%/iOSLib/'
    paths:
    - '%UNITY_PROJ_REL_PATH%/Library/'
    policy: pull
  only:
  - triggers
  script:
  - python %PYTHON_CI_REPO_PATH%\UnityGenericCall\UnityTestsCall.py -buildTarget
    ios
  stage: test
  tags:
  - ios
...
