---
stages:
- check
- compile
- test
variables:
  UNITY_PROJ_REL_PATH: Project
  PYTHON_CI_REPO_PATH: C:\sp-tools-Python-CI-Scripts

Check_MergeConflict_Files:
  only:
  - triggers
  script:
  - %CI_PROJECT_DIR%\scripts\check-merge-conflicts.sh
  stage: check
Copy_New_Branch_Cache:
  only:
  - triggers
  script:
  - python %PYTHON_CI_REPO_PATH%\GenericJobs\CopyCache.py -s master
  stage: compile
Create_UnityCache_Android:
  cache:
    key: '%CI_COMMIT_REF_NAME%/AndroidLib/'
    paths:
    - '%UNITY_PROJ_REL_PATH%/Library/'
  only:
  - triggers
  script:
  - python %PYTHON_CI_REPO_PATH%\UnityGenericCall\UnityImportProject.py -buildTarget
    android
  stage: compile
Create_UnityCache_iOS:
  cache:
    key: '%CI_COMMIT_REF_NAME%/iOSLib/'
    paths:
    - '%UNITY_PROJ_REL_PATH%/Library/'
  only:
  - triggers
  script:
  - python %PYTHON_CI_REPO_PATH%\UnityGenericCall\UnityImportProject.py -buildTarget
    ios
  stage: compile

Android_Unity_Tests:
  artifacts:
    paths:
    - '%CI_PROJECT_DIR%/UnityLog/'
    when: always
  cache:
    key: '%CI_COMMIT_REF_NAME%/AndroidLib/'
    paths:
    - '%UNITY_PROJ_REL_PATH%/Library/'
    policy: pull
  only:
  - triggers
  script:
  - python %PYTHON_CI_REPO_PATH%\UnityGenericCall\UnityTestsCall.py -buildTarget
    android
  stage: test
iOS_Unity_Tests:
  artifacts:
    paths:
    - '%CI_PROJECT_DIR%/UnityLog/'
    when: always
  cache:
    key: '%CI_COMMIT_REF_NAME%/iOSLib/'
    paths:
    - '%UNITY_PROJ_REL_PATH%/Library/'
    policy: pull
  only:
  - triggers
  script:
  - python %PYTHON_CI_REPO_PATH%\UnityGenericCall\UnityTestsCall.py -buildTarget
    ios
  stage: test
...
