#!/bin/bash
export CCACHE_CPP2=yes
export CCACHE_LOGFILE=/tmp/ccache.log
export CCACHE_CONFIGPATH=~/.ccache/ccache.conf  
export CCACHE_SLOPPINESS=time_macros,pch_defines

if [ -z "$DEVELOPER_DIR" ]; then 
  XCODE_DIR="$(xcode-select -p)"
  echo "Developer dir is not set, trying our best ($XCODE_DIR)"; 
else 
  XCODE_DIR="$DEVELOPER_DIR"
fi

TMP="$@"
exec /usr/local/bin/ccache $XCODE_DIR/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -Qunused-arguments ${TMP#-x c++ }
