#!/bin/bash
export CCACHE_CPP2=yes
export CCACHE_CONFIGPATH=~/.ccache/ccache.conf
export CCACHE_SLOPPINESS=time_macros,pch_defines
export PWD=`pwd`
export CCACHE_PREFIX="$PWD/distcc/distcc"

echo "$PWD" 
echo "$CCACHE_PREFIX" 

if [ -z "$DEVELOPER_DIR" ]; then 
  XCODE_DIR="$(xcode-select -p)"
  echo "Developer dir is not set, trying our best ($XCODE_DIR)"; 
else 
  XCODE_DIR="$DEVELOPER_DIR"
fi

TMP="$@"
# Xcode runs this command to know which version of the Address Sanitizer library to look for: 
# sh -c $(CC) -v -E -dM -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -x c -c /dev/null 2>&1
# so this is a tiny "hack" to let it find it
if [[ $TMP == *"-v "* ]]; then
	exec $XCODE_DIR/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -Qunused-arguments ${TMP#-x c++ }
else
	exec /usr/local/bin/ccache $XCODE_DIR/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -Qunused-arguments ${TMP#-x c++ }
fi
