using System.Collections.Generic;

namespace SocialPoint.TransparentBundles
{
    public class Bundle
    {
        public string Name = "";
        public Dictionary<BundlePlaform, int> Size;
        public bool IsAutogenerated;
        public bool IsLocal;
        public Asset Asset;

        public List<Bundle> Parents;
        public Dictionary<BundlePlaform, string> Url;

        public BundleStatus Status;
        public Dictionary<int, BundleOperation> OperationQueue;
        public string Log;
        public bool IsRequested;

        public Bundle(string name, Dictionary<BundlePlaform, int> size, bool isAutogenerated, bool isLocal, Asset asset, List<Bundle> parents, Dictionary<BundlePlaform, string> url, BundleStatus status, Dictionary<int, BundleOperation> operationQueue, string log, bool isRequested)
        {
            Name = name;
            Size = size;
            IsAutogenerated = isAutogenerated;
            IsLocal = isLocal;
            Asset = asset;
            Parents = parents;
            Url = url;
            Status = status;
            OperationQueue = operationQueue;
            Log = log;
            IsRequested = isRequested;
        }
    }

    public enum BundleStatus
    {
        Deployed,
        Processing,
        Queued,
        Warning,
        Failed
    }

    public enum BundleOperation
    {
        create_asset_bundles,
        remove_asset_bundles,
        create_local_asset_bundles,
        remove_local_asset_bundles,
        deploy_to_production
    }

    public enum BundlePlaform
    {
        ios,
        android_etc
    }
}
