#!/bin/sh

PROJECT_NAME="Project"

# Remove empty assets directory
PROJECT_DIR=$(cd "$PROJECT_NAME" && pwd)
ASSETS_DIR=$(cd "$PROJECT_DIR/Assets" && pwd)
find $ASSETS_DIR -depth -type d -empty -delete
