#!/bin/sh

ASSETS_DIR_NAME=$(find . -name 'Assets' -maxdepth 2 -type d)
PROJECT_NAME="$(basename $(dirname "$ASSETS_DIR_NAME"))"
PROJECT_DIR=$(cd "$PROJECT_NAME" && pwd)

# Remove empty directories
ASSETS_DIR=$(cd "$PROJECT_DIR/Assets" && pwd)
find $ASSETS_DIR -name '*.DS_Store' -type f -delete
find $ASSETS_DIR -type d -depth -empty -exec echo "Removing "{} \; -exec rmdir {} \; -exec rm {}.meta \;
