#!/bin/sh

PROJECT_NAME="Project"

# Remove empty directories
PROJECT_DIR=$(cd "$PROJECT_NAME" && pwd)
ASSETS_DIR=$(cd "$PROJECT_DIR/Assets" && pwd)
find $PROJECT_DIR -name '*.DS_Store' -type f -delete
find $PROJECT_DIR -depth -type d -empty -delete
