#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

REPO_PATH=$(git rev-parse --show-toplevel)

# Remove merge conflict files
find $REPO_PATH -name '*~HEAD*' -type f -delete
find $REPO_PATH -name '*.orig*' -type f -delete

# Remove empty directories
find $REPO_PATH -name '*.DS_Store' -type f -delete
find $REPO_PATH -type d -depth -empty -exec echo "Removing "{} \; -exec rmdir {} \; -exec rm {}.meta \;

# Check files with conflicts
python -B $REPO_PATH/scripts/hooks/check-merge-conflicts.py
if [ $? -ne 0 ]
then
  echo "Commit files contain merge conflicts!"
  exit 1
fi

OS="`uname`"
if [ $OS == "Darwin" ];
then

	# Reorder XCode project
	export PATH=/usr/local/bin:$PATH

	XCODE_PROJECT_DIR_NAME=$(find . -type d -wholename '*Hidden~/Sources/Apple/sp_unity_plugins')
	XCODE_PROJECT_DIR=$(cd "$XCODE_PROJECT_DIR_NAME" && pwd)

	python -B "$XCODE_PROJECT_DIR/tools/reorder_xcode_project_pre_commit.py"

	if [ $? -ne 0 ]
	then
	echo "Could not reorder Xcode project!"
	exit 1
	fi

fi

ASSETS_DIR_NAME=$(find . -name 'Assets' -maxdepth 2 -type d)
PROJECT_NAME=$(basename $(dirname "$ASSETS_DIR_NAME"))

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

git diff --cached --name-only --diff-filter=A -z $against -- "$PROJECT_NAME/Assets" | while read -d $'\0' f; do
	ext="${f##*.}"
	file="${f##*/}"
	base="${f%.*}"

	hidden_folder_mark="~"
	if echo "$base" | grep -q "$hidden_folder_mark"
	then
		continue
	fi

	if [ $OS == "Darwin" ];
	then
		if [[ "$file" =~ ^\. ]]; then
			continue
		fi
	else
		[ $(echo $file | grep "^\.") ] && continue || echo nomatch
	fi

	if [ "$ext" = "meta" ]; then
		if [ $(git ls-files --cached -- "$base" | wc -l) = 0 ]; then
			cat <<EOF
Error: Redudant meta file(A).

Meta file \`$f' is added, but \`$base' is not in the git index.

Please add \`$base' to git as well.
EOF
			exit 1
		fi
	else
		p="$f"
		while [ "$p" != "$PROJECT_NAME/Assets" ]; do
			if [ $(git ls-files --cached -- "$p.meta" | wc -l) = 0 ]; then
				cat <<EOF
Error: Missing meta file(A).

Asset \`$f' is added, but \`$p.meta' is not in the git index.

Please add \`$p.meta' to git as well.
EOF
				exit 1
			fi
			p="${p%/*}"
		done
	fi
done

ret="$?"
if [ "$ret" != 0 ]; then
	exit "$ret"
fi

git diff --cached --name-only --diff-filter=D -z $against -- "$PROJECT_NAME/Assets" | while read -d $'\0' f; do
	ext="${f##*.}"
	base="${f%.*}"

	hidden_folder_mark="~"
	if echo "$base" | grep -q "$hidden_folder_mark"
	then
		continue
	fi

	if [ "$ext" = "meta" ]; then
		if [ $(git ls-files --cached -- "$base" | wc -l) != 0 ]; then
			cat <<EOF
Error: Redudant meta file(D).

Meta file \`$f' is removed, but \`$base' is still in the git index.

Please remove \`$base' from git as well.
EOF
			exit 1
		fi
	else
		p="$f"
		while [ "$p" != "$PROJECT_NAME/Assets" ]; do
			if [ $(git ls-files --cached -- "$p" | wc -l) = 0 ] && [ $(git ls-files --cached -- "$p.meta" | wc -l) != 0 ]; then
				cat <<EOF
Error: Missing meta file(D).

Asset \`$f' is removed, but \`$p.meta' is still in the git index.

Please remove \`$p.meta' from git as well.
EOF
				exit 1
			fi
			p="${p%/*}"
		done
	fi
done

ret="$?"
if [ "$ret" != 0 ]; then
	exit "$ret"
fi
